#!/usr/bin/env python3
"""
FengShui AI - Configuration Setup Script
Helps users configure their API keys easily
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv, dotenv_values

# Colors for terminal output
class Colors:
    HEADER = '\033[95m'
    CYAN = '\033[96m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text:^60}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.ENDC}\n")

def print_section(text):
    print(f"{Colors.CYAN}{Colors.BOLD}{text}{Colors.ENDC}")
    print(f"{Colors.CYAN}{'-'*len(text)}{Colors.ENDC}")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.ENDC}")

def print_error(text):
    print(f"{Colors.RED}✗ {text}{Colors.ENDC}")

def print_warning(text):
    print(f"{Colors.YELLOW}⚠ {text}{Colors.ENDC}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ {text}{Colors.ENDC}")

def check_env_file():
    """Check if .env file exists"""
    return os.path.exists('.env')

def load_current_config():
    """Load current configuration from .env"""
    if check_env_file():
        return dotenv_values('.env')
    return {}

def get_env_value(key, current_config):
    """Get current value of env variable"""
    return current_config.get(key, 'NOT SET')

def setup_deepseek():
    """Set up DeepSeek API key"""
    print_section("🤖 DeepSeek AI Chatbot Setup")
    
    print_info("DeepSeek provides affordable AI API access")
    print_info("Free tier: Usually $5-10 in free credits")
    print_info("Paid tier: ~$0.14 per million input tokens\n")
    
    print("Steps to get your API key:")
    print("1. Go to: https://platform.deepseek.com/api_keys")
    print("2. Sign up or log in")
    print("3. Create a new API key")
    print("4. Copy the key\n")
    
    api_key = input(f"{Colors.BOLD}Enter your DeepSeek API key: {Colors.ENDC}").strip()
    
    if not api_key or api_key == "YOUR_DEEPSEEK_API_KEY_HERE":
        print_error("Invalid API key")
        return False
    
    if len(api_key) < 20:
        print_warning("API key seems too short. Are you sure?")
        confirm = input(f"{Colors.BOLD}Continue anyway? (y/n): {Colors.ENDC}").lower()
        if confirm != 'y':
            return False
    
    print_success(f"DeepSeek API key configured: {api_key[:10]}...{api_key[-5:]}")
    return api_key

def update_env_file(config_dict):
    """Update or create .env file with new config"""
    current_config = load_current_config()
    current_config.update(config_dict)
    
    # Build .env content
    lines = []
    lines.append("# FengShui AI Configuration")
    lines.append("# Generated by setup script\n")
    
    # AMap
    lines.append("# AMap API Configuration")
    lines.append(f"AMAP_API_KEY={current_config.get('AMAP_API_KEY', 'YOUR_AMAP_API_KEY_HERE')}")
    lines.append(f"AMAP_SECURITY_KEY={current_config.get('AMAP_SECURITY_KEY', 'YOUR_AMAP_SECURITY_KEY_HERE')}\n")
    
    # DeepSeek
    lines.append("# DeepSeek AI Chatbot API")
    lines.append(f"DEEPSEEK_API_KEY={current_config.get('DEEPSEEK_API_KEY', 'YOUR_DEEPSEEK_API_KEY_HERE')}")
    lines.append(f"DEEPSEEK_API_URL={current_config.get('DEEPSEEK_API_URL', 'https://api.deepseek.com/v1/chat/completions')}")
    lines.append(f"DEEPSEEK_MODEL={current_config.get('DEEPSEEK_MODEL', 'deepseek-chat')}\n")
    
    # OpenTopography
    lines.append("# OpenTopography API (optional)")
    lines.append(f"OPENTOPO_API_KEY={current_config.get('OPENTOPO_API_KEY', 'YOUR_OPENTOPO_API_KEY_HERE')}\n")
    
    # Flask
    lines.append("# Flask Configuration")
    lines.append(f"DEBUG={current_config.get('DEBUG', 'False')}")
    lines.append(f"HOST={current_config.get('HOST', '0.0.0.0')}")
    lines.append(f"PORT={current_config.get('PORT', '5000')}\n")
    
    # HydroSHEDS
    lines.append("# HydroSHEDS (Rivers) via Google Earth Engine")
    lines.append(f"HYDROSHEDS_ENABLE={current_config.get('HYDROSHEDS_ENABLE', 'True')}")
    lines.append(f"HYDROSHEDS_GEE_SERVICE_ACCOUNT_PATH={current_config.get('HYDROSHEDS_GEE_SERVICE_ACCOUNT_PATH', 'backend/dem/service_account.json')}")
    lines.append(f"HYDROSHEDS_FLOW_ACC_DATASET={current_config.get('HYDROSHEDS_FLOW_ACC_DATASET', 'WWF/HydroSHEDS/15ACC')}")
    lines.append(f"HYDROSHEDS_FLOW_ACC_THRESHOLD={current_config.get('HYDROSHEDS_FLOW_ACC_THRESHOLD', '1')}")
    lines.append(f"HYDROSHEDS_PIXEL_SIZE_M={current_config.get('HYDROSHEDS_PIXEL_SIZE_M', '500')}")
    lines.append(f"HYDROSHEDS_RADIUS_M={current_config.get('HYDROSHEDS_RADIUS_M', '1000')}")
    
    # Write to file
    with open('.env', 'w') as f:
        f.write('\n'.join(lines))
    
    return True

def verify_deepseek_key(api_key):
    """Test the DeepSeek API key"""
    print_info("Testing DeepSeek API key...")
    
    try:
        import requests
        
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}"
        }
        
        payload = {
            "model": "deepseek-chat",
            "messages": [{"role": "user", "content": "Test"}],
            "max_tokens": 10,
            "temperature": 0.1
        }
        
        response = requests.post(
            "https://api.deepseek.com/v1/chat/completions",
            headers=headers,
            json=payload,
            timeout=10
        )
        
        if response.status_code == 200:
            print_success("DeepSeek API key is valid!")
            return True
        elif response.status_code == 401:
            print_error("Invalid API key (401 Unauthorized)")
            return False
        else:
            print_warning(f"API returned status {response.status_code}")
            print_info(f"Response: {response.text[:200]}")
            return False
    
    except requests.exceptions.RequestException as e:
        print_warning(f"Connection error: {e}")
        print_info("You can test the key later by running an analysis")
        return True
    except Exception as e:
        print_warning(f"Error testing API: {e}")
        return True

def show_current_config():
    """Display current configuration"""
    print_section("📋 Current Configuration")
    
    current_config = load_current_config()
    
    if not current_config:
        print_warning("No .env file found. Run setup to create one.\n")
        return
    
    # Display important keys
    important_keys = [
        ('DEEPSEEK_API_KEY', 'DeepSeek API Key'),
        ('DEEPSEEK_MODEL', 'DeepSeek Model'),
        ('AMAP_API_KEY', 'AMap API Key'),
    ]
    
    for key, label in important_keys:
        value = current_config.get(key, 'NOT SET')
        if value == 'NOT SET' or value == 'YOUR_DEEPSEEK_API_KEY_HERE':
            print_warning(f"{label}: NOT CONFIGURED")
        else:
            if len(value) > 15:
                display_value = f"{value[:10]}...{value[-5:]}"
            else:
                display_value = f"{'*' * len(value)}"
            print_success(f"{label}: {display_value}")
    
    print()

def main():
    """Main setup flow"""
    print_header("🔮 FengShui AI - Configuration Setup")
    
    print(f"{Colors.CYAN}This will help you configure your API keys.{Colors.ENDC}\n")
    
    if check_env_file():
        print_info(".env file already exists")
        show_current_config()
        
        action = input(f"{Colors.BOLD}What would you like to do? (1=Add/Update Key, 2=View Config, 3=Exit): {Colors.ENDC}").strip()
        
        if action == '2':
            show_current_config()
            return
        elif action != '1':
            print_info("Exiting setup")
            return
    else:
        print_warning(".env file not found. Creating new configuration...\n")
    
    # Setup DeepSeek
    api_key = setup_deepseek()
    
    if api_key:
        # Update .env file
        try:
            update_env_file({
                'DEEPSEEK_API_KEY': api_key,
                'DEEPSEEK_API_URL': 'https://api.deepseek.com/v1/chat/completions',
                'DEEPSEEK_MODEL': 'deepseek-chat'
            })
            print_success(".env file created/updated successfully!")
            
            # Verify the key
            verify_deepseek_key(api_key)
            
            print_section("✅ Setup Complete!")
            print(f"{Colors.GREEN}Your API key is now configured.{Colors.ENDC}")
            print(f"{Colors.BLUE}Next steps:{Colors.ENDC}")
            print("1. Restart your Flask backend server")
            print("2. Reload your frontend in the browser")
            print("3. The chatbot should now be fully functional\n")
            
        except Exception as e:
            print_error(f"Failed to update .env file: {e}\n")
    else:
        print_error("Setup cancelled. No changes made.\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{Colors.YELLOW}Setup cancelled by user{Colors.ENDC}\n")
        sys.exit(0)
    except Exception as e:
        print_error(f"Setup error: {e}\n")
        sys.exit(1)
